
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 109
#define YY_END_OF_BUFFER 110
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[342] =
    {   0,
        0,    0,    0,    0,  110,  108,  106,  107,  105,   86,
      108,  108,   74,   87,  108,   95,   96,   72,   70,   91,
       71,   92,   73,  102,   89,   90,   77,   83,   79,   99,
       99,   93,   94,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   97,   88,   98,
        6,    7,    6,   82,    0,  104,    0,    0,   84,    0,
        0,   75,  102,   76,  101,    5,    9,  100,  102,   78,
       81,   80,   99,   99,   99,   99,   99,   99,   99,   99,
       14,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   18,   99,   99,   99,   99,   99,

       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   85,    8,    0,  103,    9,  100,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   13,   99,   99,   99,   99,
       99,   99,   99,   99,   25,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,    0,   12,   99,   23,   28,
       99,   99,   99,   99,   99,   19,   99,   31,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   62,   64,   99,   99,   65,   67,   99,   99,

       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   10,   99,   99,   99,    0,   16,   99,
       11,   99,   99,   99,   99,   99,   99,   58,   99,   59,
       27,   35,   99,   60,   61,   36,   99,   99,   38,   99,
       40,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       56,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   15,    0,   99,   99,   99,   26,   29,
       32,   33,   99,   99,   99,   55,   99,   41,   99,   69,
       50,   99,   42,   43,   20,   44,   45,   99,   99,   57,
       21,   22,   99,   48,   68,   99,   99,   99,    0,   99,

       99,   24,   34,   49,   37,   39,   63,   66,   46,   51,
       47,   99,   53,   99,    0,    0,    0,   30,   17,   52,
       54,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    4,    0,    2,    3,    1,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,    1,    1,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   28,   27,   29,   27,   27,
       27,   27,   27,   27,   30,   27,   27,   27,   27,   27,
       31,   32,   33,    4,   27,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   27,   43,   44,   45,   46,
       47,   48,   27,   49,   50,   51,   52,   53,   54,   27,
       27,   27,   55,   56,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[58] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        1,    1,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1
    } ;

static const flex_int16_t yy_base[347] =
    {   0,
        0,    0,   55,   56,  394,  395,  395,  395,  395,  368,
      385,   58,  395,  381,  358,  395,  395,  395,   46,  395,
       51,   44,   59,   56,  395,  395,  364,  363,  362,    0,
      356,  395,  395,  336,   41,   42,  340,   71,  345,   40,
       43,  344,   76,  336,  334,   51,  338,  395,  322,  395,
      395,  395,  358,  395,  369,  395,   89,  326,  395,  363,
       73,  395,   76,  395,   82,  395,    0,   84,  111,  395,
      395,  395,    0,  345,  334,  321,  336,  331,  322,  328,
      314,  315,  320,   86,  319,  324,  314,   68,   87,  322,
      102,  321,  309,  306,    0,  305,  306,  312,  302,   96,

      318,  300,  301,  313,  299,  305,  298,  305,  296,  301,
      293,  293,  298,  395,  395,  305,  395,    0,  123,  310,
      303,  298,  286,  300,   95,  299,  297,  293,  283,  290,
      279,  275,  275,  291,  286,    0,  281,  271,   53,  287,
      110,  276,  277,  113,    0,  269,  271,  115,  269,  281,
      262,  271,  266,   99,  269,  276,  257,  257,  114,  269,
      257,  268,  262,  254,  258,  261,    0,  257,    0,    0,
      250,  247,  255,  244,  251,    0,  244,    0,  246,  242,
      118,  240,  244,  243,  119,  251,  239,  240,  242,  236,
      239,  231,  240,    0,  233,  228,  237,    0,  224,  231,

      226,  228,  234,  220,  236,  224,  223,  232,  231,  224,
      231,  213,  221,    0,  216,  219,  222,  214,    0,  220,
        0,  211,  212,  217,  216,  204,  211,    0,  204,    0,
        0,    0,  199,    0,    0,    0,  211,  209,    0,  200,
        0,  208,  211,  195,  204,  208,  203,  202,  193,  199,
        0,  194,  180,  170,  181,  168,  177,  170,  166,  174,
      163,  157,  161,    0,  172,  154,  150,  150,    0,    0,
        0,    0,  150,  160,  152,    0,  147,    0,  147,    0,
        0,  146,    0,    0,    0,    0,    0,  155,  154,    0,
        0,    0,  154,    0,    0,  140,  151,  138,  154,  139,

      149,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  147,    0,  145,  162,  135,  134,    0,    0,    0,
        0,  127,  119,  109,  119,   92,   77,   75,  168,  169,
      170,  137,  175,  139,   69,  395,   44,  395,  395,  395,
      395,  222,  226,  230,   58,  234
    } ;

static const flex_int16_t yy_def[347] =
    {   0,
      341,    1,  342,  342,  341,  341,  341,  341,  341,  341,
      343,  341,  341,  341,  344,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  345,
      345,  341,  341,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  341,  341,  341,
      341,  341,  341,  341,  343,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  346,  341,  341,  341,
      341,  341,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  341,  341,  341,  341,  346,  341,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  341,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  341,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  341,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  341,  345,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  341,  341,  341,  345,  345,  345,
      345,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
        0,  341,  341,  341,  341,  341
    } ;

static const flex_int16_t yy_nxt[453] =
    {   0,
        6,    7,    8,    6,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       24,   25,   26,   27,   28,   29,   30,   30,   31,   30,
       32,    6,   33,   30,   34,   35,   36,   37,   38,   39,
       30,   40,   30,   30,   30,   30,   30,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   50,   52,   52,   57,
       62,   73,   57,   65,   65,   63,   63,   64,   53,   53,
       63,   63,   66,   68,   76,   69,   69,   67,   95,   80,
       97,   77,  340,  117,   78,   96,  186,   79,   81,  109,
       57,   98,   60,   57,   99,   63,   63,  110,  111,  187,

      112,   65,   65,  119,  119,   58,   83,  339,   84,   85,
       86,  101,  330,  102,   87,  135,  136,   88,   89,   90,
       91,   92,  329,  103,   93,  104,  105,  328,   68,  106,
       69,   69,  130,  204,  131,  137,   58,  140,  138,  141,
      149,  150,  119,  119,  172,  173,  151,  189,  193,  152,
      197,  205,  210,  228,  234,  315,  327,  326,  315,  211,
      190,  325,  194,  315,  198,  229,  315,  230,  235,  331,
      333,  331,  331,  333,  331,  335,  333,  337,  324,  333,
      323,  322,  336,  321,  338,  320,  319,  318,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,

      302,  301,  300,  316,  317,  299,  298,  297,  296,  295,
      294,  316,  317,  293,  332,  334,  332,  292,  291,  290,
      289,  334,   51,   51,   51,   51,   55,   55,   55,   55,
       60,  288,  287,   60,  118,  286,  118,  118,  285,  284,
      283,  282,  281,  280,  279,  278,  277,  276,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  233,  232,
      231,  227,  226,  225,  224,  223,  222,  221,  220,  219,

      218,  217,  216,  215,  214,  213,  212,  209,  208,  207,
      206,  203,  202,  201,  200,  199,  196,  195,  192,  191,
      188,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  171,  170,  169,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  148,  147,  146,  145,  144,  143,  142,  139,
      134,  133,  132,  129,  128,  127,  126,  125,  124,  123,
      122,  121,  120,  117,  116,   56,  115,  114,  113,  108,
      107,  100,   94,   82,   75,   74,   72,   71,   70,   61,
       59,   56,   54,  341,    5,  341,  341,  341,  341,  341,

      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341
    } ;

static const flex_int16_t yy_chk[453] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,   12,
       19,  345,   12,   22,   22,   19,   19,   21,    3,    4,
       21,   21,   23,   24,   35,   24,   24,   23,   40,   36,
       41,   35,  337,   61,   35,   40,  139,   35,   36,   46,
       57,   41,   61,   57,   41,   63,   63,   46,   46,  139,

       46,   65,   65,   68,   68,   12,   38,  335,   38,   38,
       38,   43,  328,   43,   38,   88,   88,   38,   38,   38,
       38,   38,  327,   43,   38,   43,   43,  326,   69,   43,
       69,   69,   84,  154,   84,   89,   57,   91,   89,   91,
      100,  100,  119,  119,  125,  125,  100,  141,  144,  100,
      148,  154,  159,  181,  185,  299,  325,  324,  299,  159,
      141,  323,  144,  315,  148,  181,  315,  181,  185,  329,
      330,  331,  329,  330,  331,  332,  333,  334,  322,  333,
      317,  316,  332,  314,  334,  312,  301,  300,  298,  297,
      296,  293,  289,  288,  282,  279,  277,  275,  274,  273,

      268,  267,  266,  299,  299,  265,  263,  262,  261,  260,
      259,  315,  315,  258,  329,  330,  331,  257,  256,  255,
      254,  333,  342,  342,  342,  342,  343,  343,  343,  343,
      344,  253,  252,  344,  346,  250,  346,  346,  249,  248,
      247,  246,  245,  244,  243,  242,  240,  238,  237,  233,
      229,  227,  226,  225,  224,  223,  222,  220,  218,  217,
      216,  215,  213,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  197,  196,  195,
      193,  192,  191,  190,  189,  188,  187,  186,  184,  183,
      182,  180,  179,  177,  175,  174,  173,  172,  171,  168,

      166,  165,  164,  163,  162,  161,  160,  158,  157,  156,
      155,  153,  152,  151,  150,  149,  147,  146,  143,  142,
      140,  138,  137,  135,  134,  133,  132,  131,  130,  129,
      128,  127,  126,  124,  123,  122,  121,  120,  116,  113,
      112,  111,  110,  109,  108,  107,  106,  105,  104,  103,
      102,  101,   99,   98,   97,   96,   94,   93,   92,   90,
       87,   86,   85,   83,   82,   81,   80,   79,   78,   77,
       76,   75,   74,   60,   58,   55,   53,   49,   47,   45,
       44,   42,   39,   37,   34,   31,   29,   28,   27,   15,
       14,   11,   10,    5,  341,  341,  341,  341,  341,  341,

      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"

#include <stdio.h>
#include <stdlib.h>

char buffer[500];
int line_count=1;
int char_count=0;

int token=1;
int source=1;

#line 667 "lex.yy.c"

#line 669 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 33 "scanner.l"


#line 890 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 342 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 395 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 35 "scanner.l"
{ sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; source=0; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 36 "scanner.l"
{ sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; source=1; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 37 "scanner.l"
{ sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; token=0; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 38 "scanner.l"
{ sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; token=1; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "scanner.l"
{ sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; BEGIN COMMENT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "scanner.l"
{ sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 42 "scanner.l"
{ if(source) printf("%d:%s\n", line_count, buffer); buffer[0]='\0'; char_count=0; line_count++; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 43 "scanner.l"
{ sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; BEGIN 0; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 44 "scanner.l"
{ sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 46 "scanner.l"
{ if(token) printf("#token key:void\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 47 "scanner.l"
{ if(token) printf("#token key:const\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 48 "scanner.l"
{ if(token) printf("#token key:NULL\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 49 "scanner.l"
{ if(token) printf("#token key:for\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 50 "scanner.l"
{ if(token) printf("#token key:do\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 51 "scanner.l"
{ if(token) printf("#token key:while\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 52 "scanner.l"
{ if(token) printf("#token key:break\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 53 "scanner.l"
{ if(token) printf("#token key:continue\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 54 "scanner.l"
{ if(token) printf("#token key:if\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 55 "scanner.l"
{ if(token) printf("#token key:else\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 56 "scanner.l"
{ if(token) printf("#token key:return\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 57 "scanner.l"
{ if(token) printf("#token key:struct\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 58 "scanner.l"
{ if(token) printf("#token key:switch\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "scanner.l"
{ if(token) printf("#token key:case\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "scanner.l"
{ if(token) printf("#token key:default\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 62 "scanner.l"
{ if(token) printf("#token key:int\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 63 "scanner.l"
{ if(token) printf("#token key:double\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 64 "scanner.l"
{ if(token) printf("#token key:float\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 65 "scanner.l"
{ if(token) printf("#token key:char\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "scanner.l"
{ if(token) printf("#token key:fclose\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "scanner.l"
{ if(token) printf("#token key:clearerr\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "scanner.l"
{ if(token) printf("#token key:feof\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "scanner.l"
{ if(token) printf("#token key:ferror\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "scanner.l"
{ if(token) printf("#token key:fflush\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 72 "scanner.l"
{ if(token) printf("#token key:fgetpos\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 73 "scanner.l"
{ if(token) printf("#token key:fopen\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 74 "scanner.l"
{ if(token) printf("#token key:fread\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 75 "scanner.l"
{ if(token) printf("#token key:freopen\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 76 "scanner.l"
{ if(token) printf("#token key:fseek\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 77 "scanner.l"
{ if(token) printf("#token key:fsetpos\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 78 "scanner.l"
{ if(token) printf("#token key:ftell\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 79 "scanner.l"
{ if(token) printf("#token key:fwrite\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 80 "scanner.l"
{ if(token) printf("#token key:remove\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 81 "scanner.l"
{ if(token) printf("#token key:rename\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 82 "scanner.l"
{ if(token) printf("#token key:rewind\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 83 "scanner.l"
{ if(token) printf("#token key:setbuf\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 84 "scanner.l"
{ if(token) printf("#token key:setvbuf\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 85 "scanner.l"
{ if(token) printf("#token key:tmpfile\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 86 "scanner.l"
{ if(token) printf("#token key:tmpnam\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 87 "scanner.l"
{ if(token) printf("#token key:fprintf\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 88 "scanner.l"
{ if(token) printf("#token key:printf\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 89 "scanner.l"
{ if(token) printf("#token key:sprintf\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 90 "scanner.l"
{ if(token) printf("#token key:vfprintf\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 91 "scanner.l"
{ if(token) printf("#token key:vprintf\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 92 "scanner.l"
{ if(token) printf("#token key:vsprintf\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 93 "scanner.l"
{ if(token) printf("#token key:fscanf\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 94 "scanner.l"
{ if(token) printf("#token key:scanf\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 95 "scanner.l"
{ if(token) printf("#token key:sscanf\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 96 "scanner.l"
{ if(token) printf("#token key:fgetc\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 97 "scanner.l"
{ if(token) printf("#token key:fgets\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 98 "scanner.l"
{ if(token) printf("#token key:fputc\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 99 "scanner.l"
{ if(token) printf("#token key:fputs\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 100 "scanner.l"
{ if(token) printf("#token key:getc\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 101 "scanner.l"
{ if(token) printf("#token key:getchar\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 102 "scanner.l"
{ if(token) printf("#token key:gets\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 103 "scanner.l"
{ if(token) printf("#token key:putc\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 104 "scanner.l"
{ if(token) printf("#token key:putchar\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 105 "scanner.l"
{ if(token) printf("#token key:puts\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 106 "scanner.l"
{ if(token) printf("#token key:ungetc\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 107 "scanner.l"
{ if(token) printf("#token key:perror\n"); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 109 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 110 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 111 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 112 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 113 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 114 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 115 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 116 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 117 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 118 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 119 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 120 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 121 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 122 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 123 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 124 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 125 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 126 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 127 "scanner.l"
{ if(token) printf("#token op:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 129 "scanner.l"
{ if(token) printf("#token punc:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 130 "scanner.l"
{ if(token) printf("#token punc:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 131 "scanner.l"
{ if(token) printf("#token punc:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 132 "scanner.l"
{ if(token) printf("#token punc:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 133 "scanner.l"
{ if(token) printf("#token punc:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 134 "scanner.l"
{ if(token) printf("#token punc:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 135 "scanner.l"
{ if(token) printf("#token punc:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 136 "scanner.l"
{ if(token) printf("#token punc:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 137 "scanner.l"
{ if(token) printf("#token punc:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 138 "scanner.l"
{ if(token) printf("#token punc:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 140 "scanner.l"
{ if(token) printf("#token id:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 141 "scanner.l"
{ if(token) printf("#token double:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 142 "scanner.l"
{ if(token) printf("#token double:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 143 "scanner.l"
{ if(token) printf("#token integer:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 144 "scanner.l"
{ if(token) printf("#token char:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 104:
/* rule 104 can match eol */
YY_RULE_SETUP
#line 145 "scanner.l"
{ if(token) printf("#token string:%s\n", yytext); sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 147 "scanner.l"
{ sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 148 "scanner.l"
{ sprintf(&(buffer[char_count]), "%s", yytext); char_count+=yyleng; }
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 149 "scanner.l"
{ if(source) printf("%d:%s\n", line_count, buffer); buffer[0]='\0'; char_count=0; line_count++; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 150 "scanner.l"
{}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 152 "scanner.l"
ECHO;
	YY_BREAK
#line 1495 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 342 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 342 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 341);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 152 "scanner.l"


int main(){
    yylex();
    return 0;
}
